version: '3'
volumes:
  app_bundle_data:
  minio_data:
services:
  app:
    image: fukata/rails:ruby3.1-tcmalloc
    command: bash -c "rm -f /app/tmp/pids/app.pid && bundle install --jobs=4 --retry=3 && bundle exec rails server -p 3000 -b 0.0.0.0 --pid /app/tmp/pids/app.pid"
    environment:
      TZ: "/usr/share/zoneinfo/Etc/UTC"
      BUNDLE_PATH: /app/vendor/bundle/
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - app_bundle_data:/app/vendor/bundle
    tty: true
    stdin_open: true
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniominio
